# .github/workflows/build-extension.yml
name: Build & Package Extension

on:
  workflow_run:
    workflows: ["Lint & Format Checks"]   # exact name of the lint workflow
    branches:   [main, dev]
    types:      [completed]

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # only run if lint passed
    name: "🛠️ Build & 📦 Package"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: caramel-extension

    steps:
      - name: Download linted code from previous run
        uses: actions/download-artifact@v3
        with:
          name: source   # or simply re-checkout below if you prefer

      - name: Checkout code   # (re-checkout is fine too)
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: caramel-extension/pnpm-lock.yaml   # <- same fix as before

      - name: Install dependencies
        run: pnpm install

      - name: Build extension
        run: pnpm run build

      - name: Package extension
        run: pnpm run package

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: extension-package
          path: extension.zip
