name: Publish to Apple App Store (Safari)

on:
  workflow_run:
    workflows: ["CI – Caramel Extension"]
    types: [completed]

jobs:
  publish_safari:
    name: Publish Safari Web Extension
    runs-on: macos-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    timeout-minutes: 30
    env:
      APP_NAME: Caramel
      BUNDLE_ID: com.yourcompany.caramel
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_APP_PASSWORD: ${{ secrets.APPLE_APP_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: extension-package
          path: ./extension.zip

      - name: Unzip extension
        run: unzip -q extension.zip -d safari_src

      - name: Install signing certs & profile
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.APPLE_CERT_P12 }}
          p12-password: ${{ secrets.APPLE_CERT_PASSWORD }}
          provisioning-profile-base64: ${{ secrets.APPLE_PROVISION_PROFILE }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: Convert to Safari app
        run: |
          xcrun safari-web-extension-converter safari_src \
            --project-location SafariExtProject \
            --app-name "$APP_NAME" \
            --bundle-identifier "$BUNDLE_ID" \
            --macos-only --no-open --no-prompt --force --copy-resources

      - name: Build & archive
        run: |
          xcodebuild -project SafariExtProject/"$APP_NAME".xcodeproj \
            -scheme "$APP_NAME" -configuration Release \
            -archivePath SafariExtProject/"$APP_NAME".xcarchive \
            DEVELOPMENT_TEAM="$APPLE_TEAM_ID" archive

      - name: Export for App Store
        run: |
          xcodebuild -exportArchive \
            -archivePath SafariExtProject/"$APP_NAME".xcarchive \
            -exportOptionsPlist SafariExtProject/"$APP_NAME"/Info.plist \
            -exportPath SafariExtProject/Exported

      - name: Upload to App Store Connect
        env:
          ALTOOL_USER: ${{ env.APPLE_ID }}
          ALTOOL_PASSWORD: ${{ env.APPLE_APP_PASSWORD }}
        run: |
          xcrun altool --upload-app -f SafariExtProject/Exported/"$APP_NAME".pkg \
            -t osx -u "$ALTOOL_USER" -p "$ALTOOL_PASSWORD" --verbose