name: Publish to Chrome Web Store

on:
  workflow_run:
    workflows: ["CI – Caramel Extension"]
    types: [completed]

jobs:
  publish_chrome:
    name: Publish Chrome Extension
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: extension-package
          path: .

      - name: Publish to Chrome Web Store
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: extension.zip
          extension-id: ${{ env.EXTENSION_ID }}
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}